[package]
name = "irys-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
tokio = { version = "1.40.0", features = ["rt"] }
reth-db = { path = "../../ext/reth/crates/storage/db" }
# reth-node-bridge = { path = "../reth-node-bridge" }
irys-types = { path = "../irys-types" }
clap = "4.5.20"
api-server = { path = "../api-server" }
eyre = "0.6.8"
color-eyre = "0.6.2"
rand = "0.8.5"
