[package]
edition = "2021"
name = "irys-chain"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5.0"
clap = "4.5.20"
color-eyre = "0.6.2"
eyre = "0.6.8"
irys-c.workspace = true
irys-reth-node-bridge.workspace = true
irys-types.workspace = true
rand = "0.8.5"
rand_chacha = "0.3.1"
reth-codecs-derive.workspace = true
reth-codecs.workspace = true
reth-db-api.workspace = true
reth-db-models.workspace = true
reth-db.workspace = true
reth-primitives.workspace = true
reth.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.8"
tempfile = "3.10"
tokio = { version = "1.40.0", features = ["rt"] }


actix.workspace = true
alloy-rlp.workspace = true
alloy-serde.workspace = true
arbitrary = { workspace = true, features = [
	"derive",
] } # arbitrary.workspace = truebytes.workspace = true
bytes.workspace = true
modular-bitfield.workspace = true
test-fuzz.workspace = true
