[workspace]
exclude = ["ext/"]
members = [
    "crates/irys-chain",
    "crates/irys-types",
    "crates/primitives",
    "crates/reth-node-bridge",
]
resolver = "2"
rust-version = "1.82"

[workspace.package]
edition = "2021"
rust-version = "1.82"

[workspace.dependencies]
alloy-consensus = { path = "./ext/alloy/crates/consensus", default-features = false }
alloy-eips = { path = "./ext/alloy/crates/eips", default-features = false }
alloy-genesis = { path = "./ext/alloy/crates/genesis", default-features = false }
alloy-primitives = { path = "./ext/alloy-core/crates/primitives", default-features = false }
alloy-rlp = "0.3.4"
alloy-rpc-types-engine = { path = "./ext/alloy/crates/rpc-types-engine" }
alloy-serde = { path = "./ext/alloy/crates/serde", default-features = false }
arbitrary = "1.3"
bytes = "1.5"
derive_more = { version = "1", features = ["full"] }
modular-bitfield = "0.11.2"
proptest-derive = "0.5"
serde = { version = "1.0", default-features = false }
serde_json = "1.0.94"
test-fuzz = "6"
thiserror = "1.0"


[patch.crates-io]
revm = { path = "./ext/revm/crates/revm" }
revm-primitives = { path = "./ext/revm/crates/primitives" }

# alloy
alloy = { path = "./ext/alloy/crates/alloy" }
alloy-consensus = { path = "./ext/alloy/crates/consensus" }
alloy-contract = { path = "./ext/alloy/crates/contract" }
alloy-eip7547 = { path = "./ext/alloy/crates/eip7547" }
alloy-eips = { path = "./ext/alloy/crates/eips" }
alloy-genesis = { path = "./ext/alloy/crates/genesis" }
alloy-json-rpc = { path = "./ext/alloy/crates/json-rpc" }
alloy-network = { path = "./ext/alloy/crates/network" }
alloy-network-primitives = { path = "./ext/alloy/crates/network-primitives" }
alloy-node-bindings = { path = "./ext/alloy/crates/node-bindings" }
alloy-provider = { path = "./ext/alloy/crates/provider" }
alloy-pubsub = { path = "./ext/alloy/crates/pubsub" }
alloy-rpc-client = { path = "./ext/alloy/crates/rpc-client" }
alloy-rpc-types = { path = "./ext/alloy/crates/rpc-types" }
alloy-rpc-types-admin = { path = "./ext/alloy/crates/rpc-types-admin" }
alloy-rpc-types-anvil = { path = "./ext/alloy/crates/rpc-types-anvil" }
alloy-rpc-types-beacon = { path = "./ext/alloy/crates/rpc-types-beacon" }
alloy-rpc-types-debug = { path = "./ext/alloy/crates/rpc-types-debug" }
alloy-rpc-types-engine = { path = "./ext/alloy/crates/rpc-types-engine" }
alloy-rpc-types-eth = { path = "./ext/alloy/crates/rpc-types-eth" }
alloy-rpc-types-mev = { path = "./ext/alloy/crates/rpc-types-mev" }
alloy-rpc-types-trace = { path = "./ext/alloy/crates/rpc-types-trace" }
alloy-rpc-types-txpool = { path = "./ext/alloy/crates/rpc-types-txpool" }
alloy-serde = { path = "./ext/alloy/crates/serde" }
alloy-signer = { path = "./ext/alloy/crates/signer" }
alloy-signer-aws = { path = "./ext/alloy/crates/signer-aws" }
alloy-signer-gcp = { path = "./ext/alloy/crates/signer-gcp" }
alloy-signer-ledger = { path = "./ext/alloy/crates/signer-ledger" }
alloy-signer-local = { path = "./ext/alloy/crates/signer-local" }
alloy-signer-trezor = { path = "./ext/alloy/crates/signer-trezor" }
alloy-transport = { path = "./ext/alloy/crates/transport" }
alloy-transport-http = { path = "./ext/alloy/crates/transport-http" }
alloy-transport-ipc = { path = "./ext/alloy/crates/transport-ipc" }
alloy-transport-ws = { path = "./ext/alloy/crates/transport-ws" }

# alloy-core
alloy-core = { path = "./ext/alloy-core/crates/core" }
alloy-dyn-abi = { path = "./ext/alloy-core/crates/dyn-abi" }
alloy-json-abi = { path = "./ext/alloy-core/crates/json-abi" }
alloy-primitives = { path = "./ext/alloy-core/crates/primitives" }
alloy-sol-macro = { path = "./ext/alloy-core/crates/sol-macro" }
alloy-sol-macro-expander = { path = "./ext/alloy-core/crates/sol-macro-expander" }
alloy-sol-macro-input = { path = "./ext/alloy-core/crates/sol-macro-input" }
alloy-sol-type-parser = { path = "./ext/alloy-core/crates/sol-type-parser" }
alloy-sol-types = { path = "./ext/alloy-core/crates/sol-types" }
syn-solidity = { path = "./ext/alloy-core/crates/syn-solidity" }
