[package]
name = "irys-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
irys-types.workspace = true
irys-storage.workspace = true
eyre.workspace = true

[lints]
workspace = true
