[package]
name = "irys-types"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.8"
color-eyre = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
fixed-hash = "0.8.0"
uint = "0.9.5"
base58 = "0.2.0"
base64-url = "2.0.0"
rand = "0.8.5"
