[package]
edition = "2021"
name = "reth-node-bridge"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rustler = {version = "0.32.1", features = ["nif_version_2_17"]}
# reth = {git = "https://github.com/paradigmxyz/reth" }

reth = { path = "../../ext/reth/bin/reth" }
reth-auto-seal-consensus = { path = "../../ext/reth/crates/consensus/auto-seal" }
reth-basic-payload-builder = { path = "../../ext/reth/crates/payload/basic" }
reth-beacon-consensus = { path = "../../ext/reth/crates/consensus/beacon" }
reth-cli-runner = { path = "../../ext/reth/crates/cli/runner" }
reth-consensus = { path = "../../ext/reth/crates/consensus/consensus" }
reth-db = { path = "../../ext/reth/crates/storage/db" }
reth-ethereum-payload-builder = { path = "../../ext/reth/crates/payload/ethereum" }
reth-exex = { path = "../../ext/reth/crates/exex" }
reth-interfaces = { path = "../../ext/reth/crates/interfaces" }
reth-node-api = { path = "../../ext/reth/crates/node/api" }
reth-node-core = { path = "../../ext/reth/crates/node-core" }
reth-node-ethereum = { path = "../../ext/reth/crates/ethereum/node" }
reth-node-events = { path = "../../ext/reth/crates/node/events" }
reth-payload-builder = { path = "../../ext/reth/crates/payload/builder" }
reth-primitives = { path = "../../ext/reth/crates/primitives" }
reth-provider = { path = "../../ext/reth/crates/storage/provider" }
reth-rpc-engine-api = { path = "../../ext/reth/crates/rpc/rpc-engine-api" }
reth-rpc-types = { path = "../../ext/reth/crates/rpc/rpc-types" }
reth-stages = { path = "../../ext/reth/crates/stages" }
reth-tracing = { path = "../../ext/reth/crates/tracing" }


alloy-rlp = "0.3.5"
clap = "4.5.4"
eyre = "0.6.12"
futures-util = "0.3.30"
jsonrpsee = "0.22"
jsonrpsee-core = "0.22"
jsonrpsee-types = "0.22"
new_type = "0.4.1"
once_cell = "1.19.0"
patch-crate = "0.1.9"
serde = "1.0.203"
serde_json = "1.0.117"
thiserror = "1.0.61"
tikv-jemallocator = "0.5.4"
tokio = "1.37.0"
tokio-stream = "0.1.15"
tracing = "0.1.40"

[features]
default = ["jemalloc"]
jemalloc = []
