[package]
edition = "2021"
name = "reth-node-bridge"
version = "0.1.0"

[dependencies]
# rustler = {version = "0.32.1", features = ["nif_version_2_17"]}
# reth = {git = "https://github.com/paradigmxyz/reth" }

# alloy-eips = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }
# alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }
# alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }

alloy-eips.workspace = true
alloy-rpc-types.workspace = true

alloy-signer-local.workspace = true
irys-primitives.workspace = true
reth = { path = "../../ext/reth/bin/reth" }
reth-chainspec = { path = "../../ext/reth/crates/chainspec" }
reth-cli = { path = "../../ext/reth/crates/cli/cli" }
reth-cli-commands = { path = "../../ext/reth/crates/cli/commands" }
reth-cli-runner = { path = "../../ext/reth/crates/cli/runner" }
reth-cli-util = { path = "../../ext/reth/crates/cli/util" }
reth-db = { path = "../../ext/reth/crates/storage/db" }
reth-ethereum-cli = { path = "../../ext/reth/crates/ethereum/cli" }
reth-node-builder = { path = "../../ext/reth/crates/node/builder" }
reth-node-core = { path = "../../ext/reth/crates/node/core" }
reth-node-ethereum = { path = "../../ext/reth/crates/ethereum/node" }
reth-node-metrics = { path = "../../ext/reth/crates/node/metrics" }
# reth-auto-seal-consensus = { path = "../../ext/reth/crates/consensus/auto-seal" }
# reth-basic-payload-builder = { path = "../../ext/reth/crates/payload/basic" }
reth-beacon-consensus = { path = "../../ext/reth/crates/consensus/beacon" }
# reth-cli-runner = { path = "../../ext/reth/crates/cli/runner" }
# reth-codecs = { path = "../../ext/reth/crates/storage/codecs" }
# reth-config = { path = "../../ext/reth/crates/config" }
# reth-consensus = { path = "../../ext/reth/crates/consensus/consensus" }
# reth-db = { path = "../../ext/reth/crates/storage/db" }
# reth-db-common = { path = "../../ext/reth/crates/storage/db-common" }
reth-e2e-test-utils = { path = "../../ext/reth/crates/e2e-test-utils" }
# reth-evm = { path = "../../ext/reth/crates/evm" }
reth-exex = { path = "../../ext/reth/crates/exex/exex" }
# reth-interfaces = { path = "../../ext/reth/crates/interfaces" }
reth-consensus-debug-client = { path = "../../ext/reth/crates/consensus/debug-client" }
reth-engine-service = { path = "../../ext/reth/crates/engine/service" }
reth-engine-tree = { path = "../../ext/reth/crates/engine/tree" }
reth-engine-util = { path = "../../ext/reth/crates/engine/util" }


reth-blockchain-tree = { path = "../../ext/reth/crates/blockchain-tree" }

# reth-node-api = { path = "../../ext/reth/crates/node/api" }
# reth-node-core = { path = "../../ext/reth/crates/node-core" }
# reth-node-events = { path = "../../ext/reth/crates/node/events" }
# reth-payload-builder = { path = "../../ext/reth/crates/payload/builder" }
# reth-primitives = { path = "../../ext/reth/crates/primitives" }
reth-provider = { path = "../../ext/reth/crates/storage/provider" }
# reth-revm = { path = "../../ext/reth/crates/revm" }
# reth-rpc-engine-api = { path = "../../ext/reth/crates/rpc/rpc-engine-api" }
# reth-rpc-types = { path = "../../ext/reth/crates/rpc/rpc-types" }
# reth-stages = { path = "../../ext/reth/crates/stages" }
# reth-static-file = { path = "../../ext/reth/crates/static-file" }
reth-tracing = { path = "../../ext/reth/crates/tracing" }
# reth-transaction-pool = { path = "../../ext/reth/crates/transaction-pool" }
foldhash = { version = "0.1", default-features = false }
api-server = { path = "../api-server" }
irys-types = { path = "../irys-types" }
futures.workspace = true


revm = { path = "../../ext/revm/crates/revm" }
revm-primitives = { path = "../../ext/revm/crates/primitives" }

# alloy-rlp = "0.3.5"
bs58 = "0.5.1"
clap = "4.5.4"
eyre = "0.6.12"
futures-util = "0.3.30"
# jsonrpsee = { version = "0.22", features = ["client", "macros", "server"] }
jsonrpsee = { version = "0.24", features = ["client", "macros", "server"] }
jsonrpsee-core = "0.24"
jsonrpsee-http-client = "0.24"
jsonrpsee-types = "0.24"
new_type = "0.4.1"
once_cell = "1.19.0"
patch-crate = "0.1.9"
serde = "1.0.203"
serde_json = "1.0.117"
serde_path_to_error = "0.1"
strum = "0.26.3"
thiserror = "1.0.61"
tikv-jemallocator = "^0.6.0"
tokio = "1.37.0"
tokio-stream = "0.1.15"
tracing = "0.1.40"

[features]
default = ["jemalloc"]
jemalloc = []
